import type { PassportPreset, PaperSize } from '../types';

export const PASSPORT_PRESETS: PassportPreset[] = [
  {
    id: 'us_passport',
    name: 'United States Passport & Visa',
    country: 'United States',
    flag: '🇺🇸',
    width: 2,
    height: 2,
    unit: 'in',
    dpi: 300,
    pixelWidth: 600,
    pixelHeight: 600,
    recommendedBackground: 'White',
    backgroundColorHex: '#FFFFFF',
    fileFormat: 'jpg',
    maxSizeBytes: 240 * 1024, // 240 KB max
    notes: '2x2 inches (51x51 mm). Head must be between 1 - 1 3/8 inches from bottom of chin to top of head.',
    officialUrl: 'https://travel.state.gov/content/travel/en/passports/how-apply/photos.html',
    dateVerified: '2026-01-15'
  },
  {
    id: 'uk_passport',
    name: 'United Kingdom Passport',
    country: 'United Kingdom',
    flag: '🇬🇧',
    width: 35,
    height: 45,
    unit: 'mm',
    dpi: 300,
    pixelWidth: 413,
    pixelHeight: 531,
    recommendedBackground: 'Off-white / Light Grey',
    backgroundColorHex: '#F3F4F6',
    fileFormat: 'jpg',
    maxSizeBytes: 10 * 1024 * 1024,
    notes: '35x45 mm. Off-white or light grey background. Head height 29mm-34mm.',
    officialUrl: 'https://www.gov.uk/photos-for-passports',
    dateVerified: '2026-01-15'
  },
  {
    id: 'schengen_passport',
    name: 'Schengen / European Union Visa',
    country: 'European Union',
    flag: '🇪🇺',
    width: 35,
    height: 45,
    unit: 'mm',
    dpi: 300,
    pixelWidth: 413,
    pixelHeight: 531,
    recommendedBackground: 'Light Grey / White',
    backgroundColorHex: '#F8F9FA',
    fileFormat: 'jpg',
    notes: '35x45 mm. Neutral background, facial area 70-80% of photo.',
    officialUrl: 'https://ec.europa.eu/home-affairs/policies/visa-policy_en',
    dateVerified: '2026-01-15'
  },
  {
    id: 'canada_passport',
    name: 'Canada Passport',
    country: 'Canada',
    flag: '🇨🇦',
    width: 50,
    height: 70,
    unit: 'mm',
    dpi: 300,
    pixelWidth: 591,
    pixelHeight: 827,
    recommendedBackground: 'Plain White / Light Colour',
    backgroundColorHex: '#FFFFFF',
    fileFormat: 'jpg',
    notes: '50x70 mm. Face height 31mm-36mm. Neutral facial expression.',
    officialUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/canadian-passports/photos.html',
    dateVerified: '2026-01-15'
  },
  {
    id: 'india_passport',
    name: 'India Passport & OCI',
    country: 'India',
    flag: '🇮🇳',
    width: 51,
    height: 51,
    unit: 'mm',
    dpi: 300,
    pixelWidth: 600,
    pixelHeight: 600,
    recommendedBackground: 'Plain White',
    backgroundColorHex: '#FFFFFF',
    fileFormat: 'jpg',
    notes: '51x51 mm (2x2 inches). Frontal view, white background.',
    officialUrl: 'https://passportindia.gov.in/',
    dateVerified: '2026-01-15'
  },
  {
    id: 'nigeria_passport',
    name: 'Nigeria Passport',
    country: 'Nigeria',
    flag: '🇳🇬',
    width: 35,
    height: 45,
    unit: 'mm',
    dpi: 300,
    pixelWidth: 413,
    pixelHeight: 531,
    recommendedBackground: 'White',
    backgroundColorHex: '#FFFFFF',
    fileFormat: 'jpg',
    notes: '35x45 mm. Plain white background, neutral expression.',
    officialUrl: 'https://immigration.gov.ng/',
    dateVerified: '2026-01-15'
  },
  {
    id: 'ghana_passport',
    name: 'Ghana Passport',
    country: 'Ghana',
    flag: '🇬🇭',
    width: 35,
    height: 45,
    unit: 'mm',
    dpi: 300,
    pixelWidth: 413,
    pixelHeight: 531,
    recommendedBackground: 'White',
    backgroundColorHex: '#FFFFFF',
    fileFormat: 'jpg',
    notes: '35x45 mm. White background, ears visible.',
    officialUrl: 'https://passport.mfa.gov.gh/',
    dateVerified: '2026-01-15'
  },
  {
    id: 'china_visa',
    name: 'China Visa',
    country: 'China',
    flag: '🇨🇳',
    width: 33,
    height: 48,
    unit: 'mm',
    dpi: 300,
    pixelWidth: 390,
    pixelHeight: 567,
    recommendedBackground: 'White',
    backgroundColorHex: '#FFFFFF',
    fileFormat: 'jpg',
    notes: '33x48 mm. White background, head width 15-22mm.',
    officialUrl: 'http://www.visaforchina.org/',
    dateVerified: '2026-01-15'
  },
  {
    id: 'australia_passport',
    name: 'Australia Passport',
    country: 'Australia',
    flag: '🇦🇺',
    width: 35,
    height: 45,
    unit: 'mm',
    dpi: 300,
    pixelWidth: 413,
    pixelHeight: 531,
    recommendedBackground: 'Plain White / Light Grey',
    backgroundColorHex: '#FFFFFF',
    fileFormat: 'jpg',
    notes: '35x45 mm. Plain white or light grey background. Head height 32-36mm.',
    officialUrl: 'https://www.passports.gov.au/web/requirements/photos.aspx',
    dateVerified: '2026-01-15'
  },
  {
    id: 'japan_passport',
    name: 'Japan Passport',
    country: 'Japan',
    flag: '🇯🇵',
    width: 35,
    height: 45,
    unit: 'mm',
    dpi: 300,
    pixelWidth: 413,
    pixelHeight: 531,
    recommendedBackground: 'Plain White',
    backgroundColorHex: '#FFFFFF',
    fileFormat: 'jpg',
    notes: '35x45 mm. Plain light/white background. Head length 34mm ±2mm.',
    officialUrl: 'https://www.mofa.go.jp/mofaj/toko/passport/ic_photo.html',
    dateVerified: '2026-01-15'
  },
  {
    id: 'us_dv_lottery',
    name: 'US DV Green Card Lottery',
    country: 'United States',
    flag: '🇺🇸',
    width: 600,
    height: 600,
    unit: 'px',
    dpi: 300,
    pixelWidth: 600,
    pixelHeight: 600,
    recommendedBackground: 'White',
    backgroundColorHex: '#FFFFFF',
    fileFormat: 'jpg',
    maxSizeBytes: 240 * 1024,
    notes: 'Must be exactly 600x600 pixels. File size max 240 KB. Plain white background.',
    officialUrl: 'https://dvprogram.state.gov/',
    dateVerified: '2026-01-15'
  }
];

export const PAPER_SIZES: PaperSize[] = [
  { id: '4x6', name: '4 × 6 inches (Postcard / 10×15 cm)', widthIn: 4, heightIn: 6, widthMm: 101.6, heightMm: 152.4 },
  { id: '5x7', name: '5 × 7 inches (13×18 cm)', widthIn: 5, heightIn: 7, widthMm: 127.0, heightMm: 177.8 },
  { id: 'a4', name: 'A4 Paper (210 × 297 mm)', widthIn: 8.27, heightIn: 11.69, widthMm: 210, heightMm: 297 },
  { id: 'letter', name: 'US Letter (8.5 × 11 inches)', widthIn: 8.5, heightIn: 11, widthMm: 215.9, heightMm: 279.4 },
];
